services:
  mysql:
    image: mysql:8.0
    container_name: mysql-telegramshop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegramshop
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-telegramshop
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-telegramshop
    environment:
      - NGROK_AUTHTOKEN=24N1ZIAmdGdfQK2yxuG3OKcD3zD_4uh5cVKLcJsYQNiY3w7e1
    command:
      - "http"
      - "app:8080"
      - "--domain=striking-pelican-singular.ngrok-free.app"
    ports:
      - "4040:4040"
    depends_on:
      - app

  app:
    build: .
    container_name: app-telegramshop
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./:/app  # Монтируем весь проект в контейнер
      - ~/.m2:/root/.m2  # Кэш Maven для ускорения сборки
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/telegramshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=shop_user
      - SPRING_DATASOURCE_PASSWORD=123456
      - TELEGRAM_BOT_WEBHOOK_PATH=https://striking-pelican-singular.ngrok-free.app/webhook
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true

volumes:
  mysql-data: 